# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95c45f44864f37b0b6a16d3513257f185dee6396a3765f0c6e3ce1f700c8b3a75739311167e1561a44343c8bc8b7fde781be3819c8fc6e00851c7a9801200f3e

test:
  secret_key_base: 9c3723e64c38eff962b0ee3114a6cf6c9101e7719d4a52d945640f2c9ffd5d29f8186f75e1c8fa48b185ad68760d0c5231d6c5ce8d248f539807f5589735a5a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
